name: Build prod
on:
  push:
      branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
 
      - name: Setup Node 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Tests
        run: npm run test
      - name: Check last version
        run: node checkversion.js
      - name: Build
        run: | 
          npm i
          npm i -g webpack webpack-cli
          webpack --mode=production
      - name: Commit new bundle
        run: |
          git config --global user.name 'Douglas R. Guimarães'
          git config --global user.email 'eu@rgdoug.com'
          git add -A
          git commit -m "Automated bundle"
          git push
      

